version: "3"
services:
  webserver:
    container_name: wallet-webserver
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
    - ./:/var/www/
    - ./docker/images/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/images/nginx/sites/:/etc/nginx/conf.d/
    - ./docker/images/nginx/ssl:/etc/ssl/
  service:
    container_name: wallet-runtime
    build: .
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      Service_name: ikhoa
    working_dir: /var/www/
    volumes:
    - ./:/var/www/
    - ./docker/images/php/local.ini:/usr/local/etc/php/conf.d/local.ini
